name: random_forest_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - imbalanced-learn=0.12.3
  - scipy=1.13.1
  - jupyter=1.0.0
  - notebook=7.2.1
  - pip
  - pip:
      - category_encoders==2.6.3